const {withBrowser,preparePage,assert}=require('./browser-helper.cjs');
withBrowser(async(b,url)=>{
  const {page:p,errors:errs}=await preparePage(b);
  await p.goto(url);
  await p.waitForTimeout(700);
  const step=async(label,fn)=>{const n=errs.length; await fn(); await p.waitForTimeout(320);
    if(errs.length>n) console.log(`  ✗ ${label}: `+errs.slice(n).join(' | ')); else console.log(`  ✓ ${label}`);};
  await step('초기 렌더', async()=>{});
  await step('상세 모드', ()=>p.click('#mPro'));
  for(const t of ['thermal','matrix','reverse','sources','chain'])
    await step('탭 '+t, ()=>p.click(`#tabs button[data-tab="${t}"]`));
  await step('시나리오 AMR', ()=>p.selectOption('#scen','agv'));
  await step('시나리오 선회', ()=>p.selectOption('#scen','spin'));
  await step('시나리오 legacy', ()=>p.selectOption('#scen','legacy'));
  await step('시나리오 SUV', ()=>p.selectOption('#scen','park_suv'));
  await step('D 슬라이더', ()=>p.fill('#sD','300'));
  await step('L 슬라이더', ()=>p.fill('#sL','40'));
  await step('속도', ()=>p.fill('#sV','2.5'));
  await step('바퀴 재질 stl', ()=>p.selectOption('#sWPre','stl'));
  await step('바닥 무도장', ()=>p.selectOption('#sFPre','bare'));
  await step('크라운 입력', ()=>p.fill('#crown','300'));
  await step('크라운 해제', ()=>p.fill('#crown','0'));
  await step('직접입력 모드', ()=>p.click('[data-set="loadMode"] button[data-v="direct"]'));
  await step('선회 기동', ()=>p.click('.strip [data-set="maneuver"] button[data-v="spin"]'));
  await p.evaluate(()=>document.querySelectorAll('.grp').forEach(d=>d.open=true));
  await step('구속 OFF', ()=>p.click('[data-set="confine"] button[data-v="0"]'));
  await step('구속 ON',  ()=>p.click('[data-set="confine"] button[data-v="1"]'));
  await step('층상 OFF', ()=>p.click('[data-set="layer"] button[data-v="0"]'));
  await step('층상 ON',  ()=>p.click('[data-set="layer"] button[data-v="1"]'));
  await step('중량모드 복귀', ()=>p.click('[data-set="loadMode"] button[data-v="build"]'));
  await step('휠수 변경', ()=>p.fill('#nCol','3'));
  await step('편심 입력', ()=>p.fill('#ex','600'));
  await step('편심 복귀', ()=>p.fill('#ex','150'));
  await step('SF 변경',  ()=>p.fill('#SF','2'));
  await step('fck 0 (에러경로)', ()=>p.fill('#fck','0'));
  await step('fck 복귀', ()=>p.fill('#fck','30'));
  await step('nu 0.6 (에러경로)', ()=>p.fill('#wNu','0.6'));
  await step('nu 복귀', ()=>p.fill('#wNu','0.48'));
  await step('테마 토글', ()=>p.click('#btnTheme'));
  await step('테마 복귀', ()=>p.click('#btnTheme'));
  await step('근거 모두 열기', ()=>p.click('#btnExpand'));
  await step('간단 모드', ()=>p.click('#mEasy'));
  await step('시나리오 복귀', ()=>p.selectOption('#scen','park_sedan'));
  // fix button
  await p.selectOption('#scen','agv'); await p.waitForTimeout(400);
  const nf=await p.$$eval('#fixes .fix',e=>e.length).catch(()=>0);
  console.log('  제안 버튼 수:', nf);
  if(nf) await step('제안 적용', ()=>p.locator('#fixes .fix').first().click());
  // overflow check
  const of=await p.evaluate(()=>{const d=document.documentElement;
    return {sw:d.scrollWidth, cw:d.clientWidth, verdict:document.querySelector('#verdict h2')?.textContent};});
  console.log('  scrollWidth/clientWidth:',of.sw,'/',of.cw, '| 판정:',of.verdict);
  const nar=await p.setViewportSize({width:400,height:900}); await p.waitForTimeout(400);
  const of2=await p.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));
  console.log('  400px 폭 scroll:',of2.sw,'/',of2.cw, of2.sw>of2.cw+2?'✗ 가로 스크롤':'✓');
  console.log('\n총 오류:',errs.length);
  errs.slice(0,8).forEach(e=>console.log('   ',e));
  assert.equal(errs.length,0,errs.join(' | '));
  assert.ok(of2.sw<=of2.cw+2,'400px overflow');
}).catch(e=>{console.error(e);process.exitCode=1;});
